# Generated by Django 5.2.3 on 2025-06-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tradingName', models.CharField(max_length=255)),
                ('ownerName', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=18, unique=True)),
                ('coverageArea', models.JSONField()),
                ('address', models.JSONField()),
            ],
        ),
    ]
